### ISSUE TITLE
Implement edit sales records by date and name

### ISSUE THREAD

**Issue by HyperionNKJ** [CS2103-AY1819S1-F10-4/main#102]
Command:
"edit-sales DATE NAME [d/DATE] [n/ITEM_NAME] [q/QUANTITY SOLD] [p/ITEM_PRICE]"

**Comment by AZhiKai** [comment]
I don't think there's time for this in v1.3. Consider moving to v1.4 or v2.0.

**Comment by AZhiKai** [comment]
Is this implemented? If not, should not close it.
