### ISSUE TITLE
As a restaurant owner, I want to know the food item with the highest profit margin

### ISSUE THREAD

**Issue by rebstan97** [CS2103-AY1819S1-F10-4/main#13]
so that I can maximise the restaurant's revenue

**Comment by AZhiKai** [comment]
Medium. Need to think of implementation -- how do we know the number of sales per food that has been done since the Point-Of-Sales (POS) system is separated from this?

**Comment by rebstan97** [comment]
Low

**Comment by HyperionNKJ** [comment]
Medium
