### ISSUE TITLE
Stray file in repo

### ISSUE THREAD

**Issue by damithc** [CS2103-AY1819S1-F10-4/main#144]
Guys, you seem to have a stray file in your repo. Please remove. Always check the diff before committing, to avoid committing unindented code into the repo.

![image](https://user-images.githubusercontent.com/1673303/47407600-97635f00-d78e-11e8-8799-ac4d6d4ac900.png)

@HyperionNKJ

**Comment by AZhiKai** [comment]
Thanks Prof @damithc, we will have it removed shortly.

**Comment by HyperionNKJ** [comment]
@damithc Thanks Prof. So sorry about that. Will get it removed asap.
