### ISSUE TITLE
Recording/Editing sales auto-updates ingredient list

### ISSUE THREAD

**Issue by HyperionNKJ** [CS2103-AY1819S1-F10-4/main#147]
As discussed earlier in today's meeting, we can make MeNUS more cohesive by auto updating the ingredient list whenever a sales record is added/edited by the user. This process will be aided by the menu component. Implementation details:

For record-sales:
1) User adds sales record of a menu item.
2)  Sales component retrieves the ingredients required to make one unit of the specified menu item from the Menu component.
3) Sales component computes the total amount of each ingredient used, and deduct it from the ingredient list in Ingredient component accordingly.

For edit-sales (Applicable when name or/and quantity sold attributes are edited):
1) User edits a sales record.
2) Sales component first adds back all the deducted ingredients. For this reason, each sales record will store a new attribute: ingredientsUsed
3) If name or (name and quantity sold) is edited: See step 2-3 of "record-sales" above.
If quantity sold is edited: See step 3 of "record-sales" above. "ingredientsUsed" will be used in ingredient computation. Step 2 of "record-sales" is hence not needed. 

Design considerations:

1) Deleting sales record does not add back the deducted ingredients. Otherwise, simply deleting an obsolete past record will mean an increase in ingredients count which doesn't make sense. If user accidentally added a sales record and deducted ingredients, he/she will have to undo for the ingredients to be added back.

2) Sales record will still be added even if the following occurs:
- Item does not exist in the menu list
- List of required ingredients does not exist in menu component.
- List of required ingredients is empty
- Required ingredients' name does not match / do not exist in ingredient list
- Ingredient list has insufficient ingredients required to make the item.

This is to ensure flexibility in adding sales record. Under such scenarios, ingredient list will not be updated. Choice of restriction may be enforced in v2.0. 

3) This implementation will require a "HashMap<Ingredient, Integer> getRequiredIngredients(String)" method from the Menu component. Name of a menu item will be passed in as argument, and a HashMap should be returned, where Key = Ingredient and Value = Quantity needed. A "RequiredIngredientsNotFoundException" or "ItemNotFoundException" should be thrown otherwise.

**Comment by AZhiKai** [comment]
HashMap<Ingredient, Float> sounds better imo.

**Comment by HyperionNKJ** [comment]
Hmm you're right! Will change it.

**Comment by rebstan97** [comment]
Why will it be float?

**Comment by HyperionNKJ** [comment]
Ah. I guess representing quantity with NumUnits would be better, right?

**Comment by AZhiKai** [comment]
<Ingredient, NumUnit>? Think this would work. Since the ingredient inside wraps the NumUnit so by storing NumUnit in hashmap, it matches the object type.

**Comment by AZhiKai** [comment]
> That'll work too. But I think Integer is a bit more convenient because I can do the deduction without parsing.

Maybe @rebstan97  can better advise on that.

**Comment by rebstan97** [comment]
> That'll work too. But I think Integer is a bit more convenient because I can do the deduction without parsing.

Yup I think so too. It is more convenient to get the integer value from the hashmap then create a NumUnit class eg `new NumUnits(integer.toString())` for deduction.

**Comment by rebstan97** [comment]
@HyperionNKJ @yican95 actually do yall think it suffices to include `IngredientName` as a key in the HashMap? Since ingredient name is unique

**Comment by AZhiKai** [comment]
> @HyperionNKJ @yican95 actually do yall think it suffices to include `IngredientName` as a key in the HashMap? Since ingredient name is unique

Wouldn't `Ingredient` already encapsulate the name?

**Comment by HyperionNKJ** [comment]
I think it would suffice. Since we are only interested in the IngredientName in this case. I'm fine with both representation however.
