### ISSUE TITLE
Resolve validation of MinUnit

### ISSUE THREAD

**Issue by rebstan97** [CS2103-AY1819S1-F10-4/main#151]
`MinUnit` should not begin with 0 eg 020, 01111 should be rejected as invalid

**Comment by AZhiKai** [comment]
Other than not starting with 0, it also shouldn't start with any other non numeric digits, if that check isn't in place yet.

**Comment by rebstan97** [comment]
> Other than not starting with 0, it also shouldn't start with any other non numeric digits, if that check isn't in place yet.

Yes that has been accounted for already. Actually I think 020, 01111 etc can still be accepted, but when parsed it will be 20 and 1111. Do you agree on this?

**Comment by AZhiKai** [comment]
That's nice. Do indicate the keyword in the PR so this gets closed appropriately.
