### ISSUE TITLE
Update model interface for stockup and consume ingredient

### ISSUE THREAD

**Issue by rebstan97** [CS2103-AY1819S1-F10-4/main#175]
Method implementation needs to be changed so that it's update all-or nothing. Currently, the ingredients that fail the check `NumUnits > minUnits` or if it does not exist will not be updated but the rest will still be.

**Comment by AZhiKai** [comment]
@rebstan97  I suppose this is already fixed? Should be closed if it is.

**Comment by rebstan97** [comment]
@AZhiKai  Yes it should be closed. Sorry I missed that out.
