### ISSUE TITLE
As a restaurant owner, I want my system to be protected

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#18]
so that only authorised users can use the application.

**Comment by AZhiKai** [comment]
I vote **High** for this as this will introduce the "Authentication" feature, assuming we have an "admin" account, he'll be able to 
- make new account for his manager
- edit the account 
- delete the account

**Comment by m4dkip** [comment]
High

**Comment by AZhiKai** [comment]
This includes modifying and deleting user account.

**Comment by AZhiKai** [comment]
Fully implemented.
