### ISSUE TITLE
As a restaurant owner, I want to have my menu system logged

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#20]
so that I know what my managers have done to the menu (maybe I have a rogue staff? who knows...)

**Comment by AZhiKai** [comment]
High.

**Comment by HyperionNKJ** [comment]
High.

**Comment by AZhiKai** [comment]
Will log both succeed and failed attempts.

**Comment by AZhiKai** [comment]
To clarify, this logging refers to both the `history` command and logging of login attempts.

**Comment by AZhiKai** [comment]
Login attempts already logged into the log file. 
Basically since whatever commands executed is logged after a user is logged in, we can assume if there's a rogue stuff, we will be able to determine based on the new log files.
