### ISSUE TITLE
Menu ari and ri

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#208]
@yican95 

These two commands seem the same thing? Or rather to a common person like me, I would thing "required ingredients" and "recipe" means the same thing.

Also, with `ari` and `ri`, is there a command like `eri` or something to edit?

**Comment by yican95** [comment]
there is no commands to edit recipe and required ingredients. Use the `ari` & `ri` to edit the them.

**Comment by yican95** [comment]
Recipe is the instructions to make the dish

**Comment by AZhiKai** [comment]
Okay, thanks for the clarification~
