### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by yican95** [CS2103-AY1819S1-F10-4/main#210]
Fix UI issues.
Add animation to UI.

**Comment by AZhiKai** [comment]
Is the UI issue regarding what we discussed? I might have figured a fix, will be trying it out on my branch.

**Comment by yican95** [comment]
Ya. I going to add some small animations to the UI too

**Comment by AZhiKai** [comment]
Okay. Do you want me to shift your menu events into the package? I can undo it if you wanna do it yourself.

**Comment by AZhiKai** [comment]
UI issues should be fixed with PR #211
