### ISSUE TITLE
Optimize sequence diagram

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#265]
![image](https://user-images.githubusercontent.com/7473075/48023037-afb48000-e177-11e8-958b-119e8b816b23.png)

This image is good, but on the website/PDF, it's probably too small to see. Consider this: https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/uml.html#sequence-diagrams under `Reference Frames`

**Comment by HyperionNKJ** [comment]
You're right. I guess it would be too small to see. I have created a PR to resolve it!
