### ISSUE TITLE
To remove side navigation bar, or not?

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#268]
As you all know, we have the side navigation bar. The concern now is that user will still be able to click on it and access the data (list, select) without logging in. So to compensate for this behavior, we would also have to make these commands as "guest" commands, meaning they can be executed without user being authenticated.

I'm not sure how nice this work-around is, but I'm kind of in favor of removing the side navigation bar. 

**Pros of removing**
1. We don't need to state which commands are guest commands (e.g. find, select, list, etc). 
2. Increased code coverage (since we will be removing stuffs which Coveralls always highlight which we didn't test)
3. It won't be graded anyway, just that it looks nice to us. (remember that input UI won't be graded, only output UI will be graded).

**Cons**
1. By default they'll only strictly be able to view menus. The rest, they need to login first which sort of make sense if you think about it.
2. Rebecca's effort of finding the icon goes down the drain, and of course some code will go to waste. But we can indicate all this in the `unused` folder or something.

Thoughts?

**Comment by HyperionNKJ** [comment]
We can include an "is user logged in" check under "switchList" method in main window. If not logged in then we can throw an exception instead of displaying the list. This means the default view when the app is started must be empty.

**Comment by AZhiKai** [comment]
Hm that's one way. But I prefer the default view to be the menu though, there's no harm in displaying that. But anything else should be privatized (limited to login only).

**Comment by AZhiKai** [comment]
Also one reason I don't want do that check in `switchList` is to not involve coupling between UI and Session. Currently, username is set by listening to the `LoginEvent`.

**Comment by HyperionNKJ** [comment]
Hmm. How about declaring an `isUserAuthenticated` boolean in `MainWindow`? `LoginEvent` and `LogoutEvent` can both toggle it. Then we can do the checking in `switchList`. The default list can be set to menu.

**Comment by rebstan97** [comment]
I’m okay with us not using the icons, but I think the panel may be one thing that may differentiate our app from the normal addressbook (even though the UI may not be graded). Alternative to Kai Jun’s solution, we can  remove the handling on mouse click? The purpose of the panel would be to highlight which icon is displayed (eg if we are showing menu, the menu icon is a different colour). Something like the list panels the side panels will also stack on top of each other (with each side panel differing by only the icon highlighted). But I think Kai Jun’s solution may be more straightforward to implement.

**Comment by AZhiKai** [comment]
Yes i agree. That idea of having a boolean to track the state sounds like a good idea. Will look into that.

Thanks both!
