### ISSUE TITLE
Refactor common classes

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#275]
In our model, I realise most feature uses the `Name` class, we can thus refactor this out into a `model.common` folder and everyone can make use of it with no duplicated code. Unless the way you validate the name is totally different and unique to your feature, then this won't work.

**Comment by rebstan97** [comment]
Item name can be alphanumeric, while ingredient name only accepts alphabets so they can't be refactored this way? unless i change the ingredient name to be alphanumeric too, but that would involve modifying the implementation for `delete-ing`

**Comment by AZhiKai** [comment]
I decided to not do the refactoring due to time constraint.
