### ISSUE TITLE
Cannot show details of selected record/ingredient after returning from another list

### ISSUE THREAD

**Issue by HyperionNKJ** [CS2103-AY1819S1-F10-4/main#286]
**Describe the bug**
Selecting the already selected record/ingredient after returning from another list does not update the detail panel. The blurred restaurant image is shown instead. Only way to resolve this is to "deselect" the selected record/ingredient either by 1) editing it; or 2) selecting another record/ingredient.

This bug is of high severity because there is no way to view the details of the selected record/ingredient if it is the only record/ingredient in the list (except by editing it).

**Steps to reproduce the behavior** 
1) Select an ingredient
2) Switch to another list, say item list.
3) Return to ingredient list.
4) Select the same selected ingredient as of step 1. 
5) Observe that the details are not showing.

Bug applies to both mouse/CLI interaction.
Bug is apparent when record/ingredient list size is 1.
Bug is different from that reported in issue #203.

**Expected behavior**
Details of the selected record/ingredient should show.

**Comment by AZhiKai** [comment]
This bug is exactly the same as the one in #203. Look at how Item and ReservationListPanel is done.

**Comment by HyperionNKJ** [comment]
The bug in #203 is something like "List A is selected at entry 1, selecting entry 1 of List B does not update panel in list B."
This bug is "List B is selected at entry 1. If I change view to list A and returns to select entry 1 of list B, panel does not update." (Observe that list A does not even have to be selected). 

There is a slight difference, but I think the same solution applies.
